import type { ProjectSettings, Segment, SpeakerProfile } from './project.types'
import type { AppLocale } from '@/app/i18n'

export const SPEAKER_COLORS = ['#0ea5a8', '#8b5cf6', '#e58a2b', '#3b82f6', '#ec4899', '#22c55e', '#ef4444', '#a855f7']

const ROLE_NAMES = {
  vi: ['Nam chính', 'Nữ chính', 'Nam phụ', 'Nữ phụ', 'Người dẫn chuyện', 'Khách mời 1', 'Khách mời 2', 'Nhân vật phụ'],
  en: ['Lead male', 'Lead female', 'Supporting male', 'Supporting female', 'Narrator', 'Guest 1', 'Guest 2', 'Supporting character'],
} as const

export function speakerRoleOptions(locale: AppLocale): readonly string[] {
  return ROLE_NAMES[locale]
}

export function defaultSpeakerRole(index: number, locale: AppLocale): string {
  return ROLE_NAMES[locale][index] || (locale === 'en' ? `Character ${index + 1}` : `Nhân vật ${index + 1}`)
}

function isGeneratedSpeakerName(name: string | undefined): boolean {
  return !name || /^Người nói \d+$/.test(name) || /^Speaker \d+$/.test(name)
}

export function resolvedSpeakerProfiles(
  segments: Segment[],
  settings: ProjectSettings,
  locale: AppLocale = 'vi',
): SpeakerProfile[] {
  const ids = [...new Set(segments.map((segment) => segment.speaker).filter((id): id is string => Boolean(id)))].sort()
  return ids.map((id, index) => {
    const saved = settings.speakerProfiles?.[id]
    return {
      id,
      // Names generated by older projects stay semantic when the UI language
      // changes. Custom user names are never translated.
      name: !isGeneratedSpeakerName(saved?.name) ? saved!.name : defaultSpeakerRole(index, locale),
      color: saved?.color || SPEAKER_COLORS[index % SPEAKER_COLORS.length],
      voice: saved?.voice || settings.speakerVoices?.[id] || settings.defaultVoice,
    }
  })
}

export function speakerProfileMap(segments: Segment[], settings: ProjectSettings, locale: AppLocale = 'vi') {
  return Object.fromEntries(resolvedSpeakerProfiles(segments, settings, locale).map((profile) => [profile.id, profile]))
}

export function speakerTextColor(segment: Segment, settings: ProjectSettings): string | undefined {
  if (segment.textColor) return segment.textColor
  if (!settings.speakerCaptionColors || !segment.speaker) return undefined
  return settings.speakerProfiles?.[segment.speaker]?.color
}
